#!/bin/bash
# Script de mise a jour planifiee.
# Mise a jour des sources, puuis des packages, puis log + planif une fois par semaine a 4h00 du matin

apt-get update && apt-get upgrade -Y
log > /var/log/update_script.log
cron 0 0 7 4 0
