#!/bin/bash
# Script de mise a jour planifiee.
# planif une fois par semaine a 4h00 du matin
# Mise a jour des sources, puis des packages, puis log

crontab -e 0 4 * * 1 apt-get update && apt-get upgrade -y >> /var/log/update_script.log

