#!/bin/bash
# Script de mise a jour planifiee.
# Mise a jour des sources, puuis des packages, puis log + planif une fois
# par semaine a 4h00 du matin

crontab -e 0 4 * * 1 apt-get update && apt-get upgrade -y >> /var/log/update_script.log

