#!/bin/bash
# script qui permet de surveiller les modifications du fichier /etc/crontab
#  et envoie un mail à root si celui-ci a été modifié.
# Créez une tache plannifiée pour script tous les jours à minuit.

if ! [-e /etc/crontab.old]
then
	cp -R /etc/crontab /etc/crontab.old
	exit
fi
md5=`md5sum /etc/crontab | cut -d ' ' -f 1`
old=`md5sum /etc/crontab.old | cut -d ' ' -f 1`
if [old != md5]
	echo "Fichier crontab modifie !" | mail -s "[ALERT] /etc/crontab modified" root
	cp -R /etc/crontab /etc/crontab.old
fi

# crontab -e 
# 0 0 * * * /Documents/GitHublsauva/init/scripts/04
